spring:
  application:
    name: swift_booking

  datasource:
    url: jdbc:postgresql://localhost:5432/Swift-Booking-DB
    username: Swift-Booking-DB-Admin
    password: Swift-Booking-DB-Admin64!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Swift-Booking
          jwk-set-uri: http://localhost:8080/realms/Swift-Booking/protocol/openid-connect/certs

  data:
    rest:
      base-path: /api
      detection-strategy: annotated    

  logging:
    level:
      org:
        springframework:
          security: DEBUG          

server:
  port: 8443

keycloak-details:
  realm-url: http://localhost:8080/realms/Swift-Booking
  origin: http://localhost:8080
  realm: Swift-Booking
  client-id: swift-booking-local-client
  secret: Mbtf8aJLjtK5jv4rw8qIpEfLlslbUsgb 
  # this is the secret for the client swift-booking-backend in Keycloak. 
  # It is ONLY for the local environment.
  # when deploying I will use web hooks to set the secret in the 
  # environment variables of the server.
  
  

allowed-origins:
  - http://localhost:8080
  - http://localhost:5432
  - http://localhost:4200