spring:
  application:
    name: bookwise
  datasource:
    url: ${BOOKWISE_DB_URL:jdbc:postgresql://localhost:5432/bookwise}
    username: ${BOOKWISE_DB_USERNAME:postgres}
    password: ${BOOKWISE_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-message: always
